name: blazing-fire

services:
  test:
    container_name: playwright-test-runner
    build:
      dockerfile: docker/test.Dockerfile
      context: .
    volumes:
      - .:/app:rw # mount all project files in /app
      # anonymous volumes to avoid conflict with the host
      - /app/node_modules
      - /app/playwright/.cache
    ipc: host
    init: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9323:9323
    command: pnpm test:e2e:docker
    # todo: make report available
