name: blazing-fire

services:
  test:
    container_name: playwright-test-runner
    build:
      dockerfile: docker/test/Dockerfile
      context: .
    volumes:
      - .:/app:rw
      # anonymous volumes to avoid conflict with the host
      - /app/node_modules
      - /app/playwright/.cache
    ipc: host
    init: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NEXT_PUBLIC_SUPABASE_URL: "http://host.docker.internal:54321"
