name: CI

concurrency:
  group: ci-pr-${{ github.event.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - converted_to_draft
      - ready_for_review

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4 # uses "packageManager" version in package.json

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Node dependencies (on the host)
        run: pnpm install --frozen-lockfile

      - name: Run code formatting check
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start local supabase instance
        run: supabase start

      - name: Setup .env
        run: ./tools/scripts/setup-env.sh

      - name: Build docker images
        run: docker compose build test

      - name: Run UI tests
        if: false
        run: docker compose run --rm -P test pnpm test:ui:docker

      - name: Run E2E tests
        run: docker compose run --rm -P test pnpm test:e2e:docker
