name: CI

concurrency:
  group: ci-pr-${{ github.event.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - converted_to_draft
      - ready_for_review

env:
  E2E_TESTS_SUMMARY_TEMPLATE: .github/templates/tests/e2e/step-summary.md
  E2E_TESTS_REPORT_URL: https://nouxx.github.io/blazing-fire-v2/pr-${{ github.event.number }}/e2e
  UI_TESTS_SUMMARY_TEMPLATE: .github/templates/tests/ui/step-summary.md
  UI_TESTS_REPORT_URL: https://nouxx.github.io/blazing-fire-v2/pr-${{ github.event.number }}/ui

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4 # uses "packageManager" version in package.json

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Node dependencies (on the host)
        run: pnpm install --frozen-lockfile

      - name: Run code formatting check
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run UI tests
        id: ui-tests
        continue-on-error: true
        run: docker compose run --rm -P test pnpm test:ui:docker

      - name: Deploy UI tests reports
        if: steps.ui-tests.outcome == 'failure'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          destination_dir: ${{ env.UI_TESTS_REPORT_URL }}

      - name: Populate "step summary" template variables for UI tests
        if: steps.ui-tests.outcome == 'failure'
        run: sed -i 's|\$REPORT_URL|${{ env.UI_TESTS_REPORT_URL }}|g' ${{ env.UI_TESTS_SUMMARY_TEMPLATE }}

      - name: Add UI tests report to the step summary
        if: steps.ui-tests.outcome == 'failure'
        run: cat ${{ env.UI_TESTS_SUMMARY_TEMPLATE }} >> $GITHUB_STEP_SUMMARY

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start local supabase instance
        run: supabase start

      - name: Setup .env
        run: ./tools/scripts/setup-env.sh

      - name: Build docker images
        run: docker compose build test

      - name: Run E2E tests
        id: e2e-tests
        continue-on-error: true
        run: docker compose run --rm -P test pnpm test:e2e:docker

      - name: Deploy to GitHub Pages
        if: steps.e2e-tests.outcome == 'failure'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          destination_dir: ${{ env.E2E_TESTS_REPORT_URL }}

      - name: Populate "step summary" template for E2E tests
        if: steps.e2e-tests.outcome == 'failure'
        run: sed -i 's|\$REPORT_URL|${{ env.E2E_TESTS_REPORT_URL }}|g' ${{ env.E2E_TESTS_SUMMARY_TEMPLATE }}

      - name: Add E2E tests report to the summary
        if: steps.e2e-tests.outcome == 'failure'
        run: cat ${{ env.E2E_TESTS_SUMMARY_TEMPLATE }} >> $GITHUB_STEP_SUMMARY
